sudo: false

addons:
 apt:
   packages:

language: scala

before_cache:

cache:
  directories:

before_script:

script:

before_deploy:

deploy:
  provider: script
  script: sbt "release with-defaults skip-tests"
  on:
    condition: -e ./deploy.sbt
    all_branches: true
